# Generated by Django 4.0.6 on 2022-08-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(),
        ),
    ]
